name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: launcher.exe
          path: .

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: v8
          release_name: Release 8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}